### ISSUE TITLE
Incorrect checksums ?

### ISSUE THREAD

**Issue by snakehand** [jbangelo/fletcher#8]
let data = [0x06, 0x83, 0x0d, 0x00, 0xc5, 0x18, 0xe5, 0x08, 0xef, 0x11];
    let csum = calc_fletcher16(&data);
    println!("{:x?}", csum);

Produces: ff63

But 0xff should not be a valid output byte, since it should have been reduced modulo 255 and be output as 0.

**Comment by jbangelo** [comment]
Thanks for the report @snakehand . Sorry it took so long to get to, but I've now merged in a fix for this issue and have cut version 0.3.0 with the fix included.
